server:
  port: 8808
spring:
  data:
#    datasource:
#      jdbc-url: jdbc:mysql://10.5.0.182:3306/sit_kayak_fxgj?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
#      initialSize: 10
#      minIdle: 10
#      maxActive: 500
#      maxWait: 60000
#      username: fxgj
#      password: Kayak@20180821
#      maximum-pool-size: 100
#      pool-name: test2
    mongodb:
      uri: mongodb://clouddata:kayak20190516@10.5.0.182:27017/clouddata

#  datasource:
#    jdbc-url: jdbc:mysql://10.5.0.182:3306/kayak_fxgj?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    username: kayak_enterprise
#    password: WHDev@20160714
#    maximum-pool-size: 5
#    pool-name: rs_demo
#  datasource:
#    jdbc-url: jdbc:mysql://10.5.0.182:3306/sit_kayak_fxgj?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
#    initialSize: 10
#    minIdle: 10
#    maxActive: 500
#    maxWait: 60000
#    username: fxgj
#    password: Kayak@20180821
#    maximum-pool-size: 100
#    pool-name: test2

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        enable_lazy_load_no_trans: false
    show-sql: true
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

test2:
  datasource:
    jdbc-url: jdbc:mysql://10.5.0.182:3306/sit_kayak_fxgj?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    initialSize: 10
    minIdle: 10
    maxActive: 500
    maxWait: 60000
    username: fxgj
    password: Kayak@20180821
    maximum-pool-size: 100
    pool-name: test2